get http://localhost:3001/authToken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJEIiwiZW1haWwiOiJmMUBAIiwiZmlyc3RfbmFtZSI6ImYiLCJsYXN0X25hbWUiOiJmIiwiY3JlYXRlZF9hdCI6IjIwMjItMDYtMzBUMjE6MDI6MzIuNjM2WiIsInVwZGF0ZV9hdCI6IjIwMjItMDYtMzBUMjE6MDI6MzIuNjM2WiIsImlhdCI6MTY1NjY5NTI3M30.pu5G2_1OapT47gnMQP9V5Du0y5mYpJPLEBegFLiQWSc

###

POST http://localhost:3001/auth/login
Content-Type: application/json

{
	"email": "f1@@",
	"password": "f"
}

###

POST http://localhost:3001/auth/login
Content-Type: application/json

{
	"email": "f1@@",
	"password": "f"
}

# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJEIiwiZW1haWwiOiJmMUBAIiwiZmlyc3RfbmFtZSI6ImYiLCJsYXN0X25hbWUiOiJmIiwiY3JlYXRlZF9hdCI6IjIwMjItMDYtMzBUMjE6MDI6MzIuNjM2WiIsInVwZGF0ZV9hdCI6IjIwMjItMDYtMzBUMjE6MDI6MzIuNjM2WiIsImlhdCI6MTY1NjY5NTI3M30.pu5G2_1OapT47gnMQP9V5Du0y5mYpJPLEBegFLiQWSc